// Banlist statiche dei retro format, mai recuperate live (vedi CONTEXT.md: i retro
// format hanno F&L list storiche congelate). Fonte: Format Library
// (formatlibrary.com), la lista F&L storica di riferimento per ciascun format:
//   goat=April 2005, edison=March 2010, hat=April 2014, tengu=September 2011,
//   redu=September 2012 (Return of the Duelist). TCG.
//
// Forma "solo eccezioni": si elencano SOLO le carte forbidden/limited/semiLimited,
// raggruppate per status (come arrivano le liste pubblicate). Tutto il resto è
// implicitamente `unlimited` (3 copie). Chiave = nome carta TCG inglese, deve
// combaciare con YGOPRODeck (verifica nome↔API rimandata al validatore, vedi
// banlists.check.ts per il controllo statico oggi disponibile).
import type { BanStatus, Format } from './types';

type LimitedStatus = Exclude<BanStatus, 'unlimited'>;
/** Eccezioni di un format, raggruppate per status. Assente = `unlimited`. */
type BanGroups = Partial<Record<LimitedStatus, readonly string[]>>;

export const BANLISTS: Record<Format, BanGroups> = {
  goat: {
    forbidden: [
      'Chaos Emperor Dragon - Envoy of the End',
      'Fiber Jar',
      'Magical Scientist',
      'Makyura the Destructor',
      'Witch of the Black Forest',
      'Yata-Garasu',
      'Butterfly Dagger - Elma',
      'Change of Heart',
      'Confiscation',
      'Dark Hole',
      "Harpie's Feather Duster",
      'Mirage of Nightmare',
      'Monster Reborn',
      'Painful Choice',
      'Raigeki',
      'The Forceful Sentry',
      'Imperial Order',
    ],
    limited: [
      'Left Arm of the Forbidden One',
      'Left Leg of the Forbidden One',
      'Right Arm of the Forbidden One',
      'Right Leg of the Forbidden One',
      'Black Luster Soldier - Envoy of the Beginning',
      'Breaker the Magical Warrior',
      'Cyber Jar',
      'D.D. Warrior Lady',
      'Dark Magician of Chaos',
      'Exiled Force',
      'Exodia the Forbidden One',
      'Injection Fairy Lily',
      'Jinzo',
      'Morphing Jar',
      'Protector of the Sanctuary',
      'Reflect Bounder',
      'Sacred Phoenix of Nephthys',
      'Sangan',
      'Sinister Serpent',
      'Tribe-Infecting Virus',
      'Twin-Headed Behemoth',
      'Card Destruction',
      'Delinquent Duo',
      'Graceful Charity',
      'Heavy Storm',
      'Lightning Vortex',
      'Mage Power',
      'Mystical Space Typhoon',
      'Pot of Greed',
      'Premature Burial',
      'Snatch Steal',
      'Swords of Revealing Light',
      'United We Stand',
      'Call of the Haunted',
      'Ceasefire',
      'Deck Devastation Virus',
      'Magic Cylinder',
      'Mirror Force',
      'Reckless Greed',
      'Ring of Destruction',
      'Torrential Tribute',
    ],
    semiLimited: [
      'Abyss Soldier',
      'Dark Scorpion - Chick the Yellow',
      'Manticore of Darkness',
      'Marauding Captain',
      'Night Assailant',
      'Vampire Lord',
      'Creature Swap',
      'Emergency Provisions',
      'Level Limit - Area B',
      'Nobleman of Crossout',
      'Reinforcement of the Army',
      'Upstart Goblin',
      'Good Goblin Housekeeping',
      'Gravity Bind',
      'Last Turn',
    ],
  },

  edison: {
    forbidden: [
      'Black Luster Soldier - Envoy of the Beginning',
      'Chaos Emperor Dragon - Envoy of the End',
      'Cyber Jar',
      'Cyber-Stein',
      'Dark Magician of Chaos',
      'Destiny HERO - Disk Commander',
      'Fiber Jar',
      'Magical Scientist',
      'Magician of Faith',
      'Makyura the Destructor',
      'Sinister Serpent',
      'Tribe-Infecting Virus',
      'Tsukuyomi',
      'Victory Dragon',
      'Witch of the Black Forest',
      'Yata-Garasu',
      'Thousand-Eyes Restrict',
      'Dark Strike Fighter',
      'Butterfly Dagger - Elma',
      'Card of Safe Return',
      'Change of Heart',
      'Confiscation',
      'Dark Hole',
      'Delinquent Duo',
      'Dimension Fusion',
      'Graceful Charity',
      "Harpie's Feather Duster",
      'Last Will',
      'Metamorphosis',
      'Mirage of Nightmare',
      'Monster Reborn',
      'Painful Choice',
      'Pot of Greed',
      'Premature Burial',
      'Raigeki',
      'Snatch Steal',
      'The Forceful Sentry',
      'Crush Card Virus',
      'Exchange of the Spirit',
      'Imperial Order',
      'Last Turn',
      'Ring of Destruction',
      'Time Seal',
    ],
    limited: [
      'Left Arm of the Forbidden One',
      'Left Leg of the Forbidden One',
      'Right Arm of the Forbidden One',
      'Right Leg of the Forbidden One',
      'Blackwing - Gale the Whirlwind',
      'Card Trooper',
      'Chaos Sorcerer',
      'Dark Armed Dragon',
      'Elemental HERO Stratos',
      'Exodia the Forbidden One',
      'Gladiator Beast Bestiari',
      'Gorz the Emissary of Darkness',
      'Lumina, Lightsworn Summoner',
      'Marshmallon',
      'Mezuki',
      'Mind Master',
      'Morphing Jar',
      'Necro Gardna',
      'Necroface',
      'Neo-Spacian Grand Mole',
      'Night Assailant',
      'Plaguespreader Zombie',
      'Rescue Cat',
      'Sangan',
      'Snipe Hunter',
      'Spirit Reaper',
      'Summoner Monk',
      'Tragoedia',
      'Black Rose Dragon',
      'Brionac, Dragon of the Ice Barrier',
      'Goyo Guardian',
      'Advanced Ritual Art',
      'Allure of Darkness',
      'Brain Control',
      'Burial from a Different Dimension',
      'Card Destruction',
      'Charge of the Light Brigade',
      'Cold Wave',
      'Destiny Draw',
      'Emergency Teleport',
      'Foolish Burial',
      'Future Fusion',
      'Giant Trunade',
      'Heavy Storm',
      'Level Limit - Area B',
      'Limiter Removal',
      'Megamorph',
      'Mind Control',
      'Monster Gate',
      'Mystical Space Typhoon',
      'One for One',
      'Overload Fusion',
      'Reasoning',
      'Reinforcement of the Army',
      'Scapegoat',
      'Swords of Revealing Light',
      'Call of the Haunted',
      'Ceasefire',
      'Gravity Bind',
      'Magic Cylinder',
      'Magical Explosion',
      'Mind Crush',
      'Mirror Force',
      'Ojama Trio',
      'Return from the Different Dimension',
      'Solemn Judgment',
      'The Transmigration Prophecy',
      'Torrential Tribute',
      'Trap Dustshoot',
      'Wall of Revealing Light',
    ],
    semiLimited: [
      'Cyber Dragon',
      'Dandylion',
      'Destiny HERO - Malicious',
      'Goblin Zombie',
      'Honest',
      'Judgment Dragon',
      'Lonefire Blossom',
      'Treeborn Frog',
      'Demise, King of Armageddon',
      'Black Whirlwind',
      'Chain Strike',
      'Gold Sarcophagus',
      'Magical Stone Excavation',
      'United We Stand',
      'Bottomless Trap Hole',
      'Royal Decree',
      'Royal Oppression',
      'Skill Drain',
      'Ultimate Offering',
    ],
  },

  hat: {
    forbidden: [
      'Burner, Dragon Ruler of Sparks',
      'Chaos Emperor Dragon - Envoy of the End',
      'Cyber Jar',
      'Cyber-Stein',
      'Dark Magician of Chaos',
      'Destiny HERO - Disk Commander',
      'Elemental HERO Stratos',
      'Fiber Jar',
      'Fishborg Blaster',
      'Glow-Up Bulb',
      'Lightning, Dragon Ruler of Drafts',
      'Magical Scientist',
      'Makyura the Destructor',
      'Mind Master',
      'Morphing Jar',
      'Morphing Jar #2',
      'Reactan, Dragon Ruler of Pebbles',
      'Rescue Cat',
      'Sangan',
      'Sinister Serpent',
      'Stream, Dragon Ruler of Droplets',
      'Substitoad',
      'Tribe-Infecting Virus',
      'Victory Dragon',
      'Witch of the Black Forest',
      'Yata-Garasu',
      'Thousand-Eyes Restrict',
      'Brionac, Dragon of the Ice Barrier',
      'Dark Strike Fighter',
      'Goyo Guardian',
      'Trishula, Dragon of the Ice Barrier',
      'Number 16: Shock Master',
      'Wind-Up Carrier Zenmaity',
      'Brain Control',
      'Butterfly Dagger - Elma',
      'Card Destruction',
      'Card of Safe Return',
      'Change of Heart',
      'Cold Wave',
      'Confiscation',
      'Delinquent Duo',
      'Dimension Fusion',
      'Dragon Ravine',
      'Future Fusion',
      'Gateway of the Six',
      'Giant Trunade',
      'Graceful Charity',
      "Harpie's Feather Duster",
      'Heavy Storm',
      'Last Will',
      'Mass Driver',
      'Metamorphosis',
      'Mirage of Nightmare',
      'Monster Reborn',
      'Painful Choice',
      'Pot of Avarice',
      'Pot of Greed',
      'Premature Burial',
      'Raigeki',
      'Snatch Steal',
      'Spellbook of Judgment',
      'Super Rejuvenation',
      'Temple of the Kings',
      'The Forceful Sentry',
      'Crush Card Virus',
      'Exchange of the Spirit',
      'Imperial Order',
      'Last Turn',
      'Return from the Different Dimension',
      'Ring of Destruction',
      'Royal Oppression',
      'Self-Destruct Button',
      'Sixth Sense',
      'Solemn Judgment',
      'Time Seal',
      'Trap Dustshoot',
      'Ultimate Offering',
    ],
    limited: [
      'Left Arm of the Forbidden One',
      'Left Leg of the Forbidden One',
      'Right Arm of the Forbidden One',
      'Right Leg of the Forbidden One',
      'Atlantean Dragoons',
      'Black Luster Soldier - Envoy of the Beginning',
      'Blackwing - Gale the Whirlwind',
      'Blaster, Dragon Ruler of Infernos',
      'Brotherhood of the Fire Fist - Spirit',
      'Coach Soldier Wolfbark',
      'Dandylion',
      'Dark Armed Dragon',
      'Debris Dragon',
      'Deep Sea Diva',
      'Exodia the Forbidden One',
      'Genex Ally Birdman',
      'Gladiator Beast Bestiari',
      'Gorz the Emissary of Darkness',
      'Honest',
      'Inzektor Dragonfly',
      'Inzektor Hornet',
      'Magician of Faith',
      'Mermail Abyssgunde',
      'Neo-Spacian Grand Mole',
      'Night Assailant',
      'Red-Eyes Darkness Metal Dragon',
      'Redox, Dragon Ruler of Boulders',
      'Rescue Rabbit',
      'Tempest, Dragon Ruler of Storms',
      'Thunder King Rai-Oh',
      'Tidal, Dragon Ruler of Waterfalls',
      'Wind-Up Magician',
      'Evigishki Gustkraken',
      'Evigishki Mind Augus',
      'Dewloren, Tiger King of the Ice Barrier',
      'Formula Synchron',
      'Legendary Six Samurai - Shi En',
      'T.G. Hyper Librarian',
      'Allure of Darkness',
      'Book of Moon',
      'Burial from a Different Dimension',
      'Charge of the Light Brigade',
      'Dark Hole',
      'Dimensional Fissure',
      'Divine Wind of Mist Valley',
      'Final Countdown',
      'Foolish Burial',
      'Gold Sarcophagus',
      'Infernity Launcher',
      'Limiter Removal',
      'Mind Control',
      'Monster Gate',
      'One Day of Peace',
      'One for One',
      'Reinforcement of the Army',
      'Rekindling',
      'Royal Tribute',
      'Sacred Sword of Seven Stars',
      'Spellbook of Fate',
      'Bottomless Trap Hole',
      'Ceasefire',
      'Compulsory Evacuation Device',
      'Eradicator Epidemic Virus',
      'Infernity Barrier',
      'Macro Cosmos',
      'Magical Explosion',
      'Solemn Warning',
      'Soul Drain',
      'The Transmigration Prophecy',
      'Torrential Tribute',
      'Wall of Revealing Light',
    ],
    semiLimited: [
      'Card Trooper',
      'Chaos Sorcerer',
      'Lonefire Blossom',
      'Necroface',
      'Reborn Tengu',
      'Summoner Monk',
      'Tragoedia',
      'Advanced Ritual Art',
      'Chain Strike',
      'Hieratic Seal of Convocation',
      'Reasoning',
      'Dimensional Prison',
      'Mirror Force',
      'Ojama Trio',
    ],
  },

  tengu: {
    forbidden: [
      'Chaos Emperor Dragon - Envoy of the End',
      'Cyber Jar',
      'Cyber-Stein',
      'Dark Magician of Chaos',
      'Destiny HERO - Disk Commander',
      'Fiber Jar',
      'Fishborg Blaster',
      'Magical Scientist',
      'Magician of Faith',
      'Makyura the Destructor',
      'Mind Master',
      'Rescue Cat',
      'Sinister Serpent',
      'Substitoad',
      'Tribe-Infecting Virus',
      'Tsukuyomi',
      'Victory Dragon',
      'Witch of the Black Forest',
      'Yata-Garasu',
      'Thousand-Eyes Restrict',
      'Dark Strike Fighter',
      'Goyo Guardian',
      'Brain Control',
      'Butterfly Dagger - Elma',
      'Card of Safe Return',
      'Change of Heart',
      'Cold Wave',
      'Confiscation',
      'Delinquent Duo',
      'Dimension Fusion',
      'Giant Trunade',
      'Graceful Charity',
      "Harpie's Feather Duster",
      'Last Will',
      'Mass Driver',
      'Metamorphosis',
      'Mirage of Nightmare',
      'Painful Choice',
      'Pot of Greed',
      'Premature Burial',
      'Raigeki',
      'Snatch Steal',
      'Temple of the Kings',
      'The Forceful Sentry',
      'Crush Card Virus',
      'Exchange of the Spirit',
      'Imperial Order',
      'Last Turn',
      'Ring of Destruction',
      'Royal Oppression',
      'Time Seal',
    ],
    limited: [
      'Left Arm of the Forbidden One',
      'Left Leg of the Forbidden One',
      'Right Arm of the Forbidden One',
      'Right Leg of the Forbidden One',
      'Black Luster Soldier - Envoy of the Beginning',
      'Blackwing - Gale the Whirlwind',
      'Blackwing - Kalut the Moon Shadow',
      'Dandylion',
      'Dark Armed Dragon',
      'Debris Dragon',
      'Elemental HERO Stratos',
      'Exodia the Forbidden One',
      'Gladiator Beast Bestiari',
      'Gorz the Emissary of Darkness',
      'Honest',
      'Lonefire Blossom',
      'Lumina, Lightsworn Summoner',
      'Marshmallon',
      'Mezuki',
      'Morphing Jar',
      'Necroface',
      'Neo-Spacian Grand Mole',
      'Night Assailant',
      'Plaguespreader Zombie',
      'Sangan',
      'Brionac, Dragon of the Ice Barrier',
      'Formula Synchron',
      'Legendary Six Samurai - Shi En',
      'T.G. Hyper Librarian',
      'Trishula, Dragon of the Ice Barrier',
      'Advanced Ritual Art',
      'Allure of Darkness',
      'Black Whirlwind',
      'Book of Moon',
      'Burial from a Different Dimension',
      'Card Destruction',
      'Charge of the Light Brigade',
      'Dark Hole',
      'Emergency Teleport',
      'Foolish Burial',
      'Future Fusion',
      'Gateway of the Six',
      'Heavy Storm',
      'Infernity Launcher',
      'Level Limit - Area B',
      'Limiter Removal',
      'Mind Control',
      'Monster Gate',
      'Monster Reborn',
      'One for One',
      'Pot of Avarice',
      'Primal Seed',
      'Reasoning',
      'Reinforcement of the Army',
      'Scapegoat',
      "Shien's Smoke Signal",
      'Ceasefire',
      'Magical Explosion',
      'Mirror Force',
      'Return from the Different Dimension',
      'Solemn Judgment',
      'The Transmigration Prophecy',
      'Torrential Tribute',
      'Trap Dustshoot',
      'Wall of Revealing Light',
    ],
    semiLimited: [
      'Archlord Kristya',
      'Card Trooper',
      'Destiny HERO - Malicious',
      'Necro Gardna',
      'Summoner Monk',
      'Tragoedia',
      'Dewloren, Tiger King of the Ice Barrier',
      'Chain Strike',
      'Destiny Draw',
      'Magical Stone Excavation',
      'Royal Tribute',
      'Swords of Revealing Light',
      'Bottomless Trap Hole',
      'Call of the Haunted',
      'Magic Cylinder',
      'Mind Crush',
      'Ojama Trio',
      'Solemn Warning',
    ],
  },

  redu: {
    forbidden: [
      'Chaos Emperor Dragon - Envoy of the End',
      'Cyber Jar',
      'Cyber-Stein',
      'Dark Magician of Chaos',
      'Destiny HERO - Disk Commander',
      'Fiber Jar',
      'Fishborg Blaster',
      'Glow-Up Bulb',
      'Magical Scientist',
      'Magician of Faith',
      'Makyura the Destructor',
      'Mind Master',
      'Rescue Cat',
      'Sinister Serpent',
      'Substitoad',
      'Tribe-Infecting Virus',
      'Victory Dragon',
      'Witch of the Black Forest',
      'Yata-Garasu',
      'Thousand-Eyes Restrict',
      'Brionac, Dragon of the Ice Barrier',
      'Dark Strike Fighter',
      'Goyo Guardian',
      'Trishula, Dragon of the Ice Barrier',
      'Brain Control',
      'Butterfly Dagger - Elma',
      'Card of Safe Return',
      'Change of Heart',
      'Cold Wave',
      'Confiscation',
      'Delinquent Duo',
      'Dimension Fusion',
      'Future Fusion',
      'Giant Trunade',
      'Graceful Charity',
      "Harpie's Feather Duster",
      'Last Will',
      'Mass Driver',
      'Metamorphosis',
      'Mirage of Nightmare',
      'Painful Choice',
      'Pot of Greed',
      'Premature Burial',
      'Raigeki',
      'Snatch Steal',
      'Temple of the Kings',
      'The Forceful Sentry',
      'Crush Card Virus',
      'Exchange of the Spirit',
      'Imperial Order',
      'Last Turn',
      'Ring of Destruction',
      'Royal Oppression',
      'Time Seal',
      'Trap Dustshoot',
    ],
    limited: [
      'Left Arm of the Forbidden One',
      'Left Leg of the Forbidden One',
      'Right Arm of the Forbidden One',
      'Right Leg of the Forbidden One',
      'Black Luster Soldier - Envoy of the Beginning',
      'Blackwing - Gale the Whirlwind',
      'Chaos Sorcerer',
      'Dandylion',
      'Dark Armed Dragon',
      'Elemental HERO Stratos',
      'Exodia the Forbidden One',
      'Gladiator Beast Bestiari',
      'Gorz the Emissary of Darkness',
      'Honest',
      'Inzektor Dragonfly',
      'Inzektor Hornet',
      'Lonefire Blossom',
      'Mezuki',
      'Morphing Jar',
      'Necroface',
      'Neo-Spacian Grand Mole',
      'Night Assailant',
      'Plaguespreader Zombie',
      'Red-Eyes Darkness Metal Dragon',
      'Sangan',
      'Spore',
      'T.G. Striker',
      'Tsukuyomi',
      'Evigishki Gustkraken',
      'Formula Synchron',
      'Legendary Six Samurai - Shi En',
      'T.G. Hyper Librarian',
      'Wind-Up Carrier Zenmaity',
      'Advanced Ritual Art',
      'Allure of Darkness',
      'Black Whirlwind',
      'Book of Moon',
      'Burial from a Different Dimension',
      'Card Destruction',
      'Charge of the Light Brigade',
      'Dark Hole',
      'Foolish Burial',
      'Gateway of the Six',
      'Heavy Storm',
      'Infernity Launcher',
      'Limiter Removal',
      'Mind Control',
      'Monster Gate',
      'Monster Reborn',
      'One for One',
      'Pot of Avarice',
      'Primal Seed',
      'Reinforcement of the Army',
      'Scapegoat',
      'Ceasefire',
      'Magical Explosion',
      'Return from the Different Dimension',
      'Solemn Judgment',
      'The Transmigration Prophecy',
      'Ultimate Offering',
      'Wall of Revealing Light',
    ],
    semiLimited: [
      'Archlord Kristya',
      'Blackwing - Kalut the Moon Shadow',
      'Card Trooper',
      'Debris Dragon',
      'Destiny HERO - Malicious',
      'Lumina, Lightsworn Summoner',
      'Reborn Tengu',
      'Rescue Rabbit',
      'Summoner Monk',
      'The Agent of Mystery - Earth',
      'Tour Guide From the Underworld',
      'Tragoedia',
      'Dewloren, Tiger King of the Ice Barrier',
      'A Hero Lives',
      'Chain Strike',
      'E - Emergency Call',
      'Hieratic Seal of Convocation',
      'Magical Stone Excavation',
      'Pot of Duality',
      'Reasoning',
      'Royal Tribute',
      "Shien's Smoke Signal",
      'Bottomless Trap Hole',
      'Mind Crush',
      'Mirror Force',
      'Ojama Trio',
      'Solemn Warning',
      'Torrential Tribute',
    ],
  },
};

const STATUSES: readonly LimitedStatus[] = ['forbidden', 'limited', 'semiLimited'];

// Mappa piatta nome→status per format, calcolata pigramente e memoizzata: la UI/
// validazione legge per nome, il file si scrive per gruppi.
const flatCache = new Map<Format, Record<string, BanStatus>>();

/** Mappa piatta {nome carta → BanStatus} del format (le carte non elencate sono `unlimited`). */
export function banlistFor(format: Format): Record<string, BanStatus> {
  const cached = flatCache.get(format);
  if (cached) return cached;
  const flat: Record<string, BanStatus> = {};
  const groups = BANLISTS[format];
  for (const status of STATUSES) for (const name of groups[status] ?? []) flat[name] = status;
  flatCache.set(format, flat);
  return flat;
}

/** BanStatus di una carta (per nome) in un format; default `unlimited`. */
export const statusOf = (format: Format, cardName: string): BanStatus =>
  banlistFor(format)[cardName] ?? 'unlimited';
